#!/usr/bin/env bash
# Script to display all active IPv4 IPs on the machine

# Use `ip` command to list IPv4 addresses associated with active interfaces
ip -4 addr show | awk '/inet / {print $2}' | cut -d'/' -f1
